// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tohwodpdccwgvdonyxeb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvaHdvZHBkY2N3Z3Zkb255eGViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NzQzNzIsImV4cCI6MjA2NTE1MDM3Mn0.GvSoyiyad8xKreMFd8qg5FNnjD0uyQOCgBXrGPpKtbk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);